// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace AmeliorateAegis.ExternalModels
{
    public partial class ContractItems
    {
        public int ContractItemID { get; set; }
        public string ContractItem { get; set; }
        public DateTime Date { get; set; }
        public int Quantity { get; set; }
        public decimal TotalAmount { get; set; }
        public int ContractID { get; set; }
    }
}