// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace AmeliorateAegis.ExternalModels
{
    public partial class Contract
    {
        public int ContractID { get; set; }
        public string ContractDescr { get; set; }
        public string ContractName { get; set; }
        public int BudgetID { get; set; }
        public decimal Date { get; set; }
    }
}