// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace AmeliorateAegis.ExternalModels
{
    public partial class Regional_Center
    {
        public int RegionalCenterID { get; set; }
        public int CenterID { get; set; }
        public int RegionalID { get; set; }
    }
}