// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace AmeliorateAegis.ExternalModels
{
    public partial class ScheduleVisit
    {
        public int ScheduleVisitID { get; set; }
        public string VisitDescr { get; set; }
        public DateTime? Date { get; set; }
        public string Time { get; set; }
        public string Duration { get; set; }
        public string ReasonForVisit { get; set; }
        public int? RegionalID { get; set; }
    }
}