// <auto-generated />
using System;
using AmeliorateAegis.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AmeliorateAegis.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211010182416_AddedApplicationUser")]
    partial class AddedApplicationUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AmeliorateAegis.Models.Attendance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("PupilId")
                        .HasColumnType("bigint");

                    b.Property<long>("TeacherId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PupilId");

                    b.HasIndex("TeacherId");

                    b.ToTable("PupilAttendance");
                });

            modelBuilder.Entity("AmeliorateAegis.Models.Centre", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressLine1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Centres");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AddressLine1 = "123 John Newton SW",
                            AddressLine2 = "Newton Park",
                            CreationTime = new DateTime(2021, 10, 10, 20, 24, 15, 319, DateTimeKind.Local).AddTicks(3914),
                            Name = "Kabega"
                        },
                        new
                        {
                            Id = 2L,
                            AddressLine1 = "237 John Newton SW",
                            AddressLine2 = "New Brighton",
                            CreationTime = new DateTime(2021, 10, 10, 20, 24, 15, 321, DateTimeKind.Local).AddTicks(7962),
                            Name = "Sol Futi"
                        },
                        new
                        {
                            Id = 3L,
                            AddressLine1 = "123 John Newton SW",
                            AddressLine2 = "Newton Park",
                            CreationTime = new DateTime(2021, 10, 10, 20, 24, 15, 321, DateTimeKind.Local).AddTicks(8043),
                            Name = "Daku"
                        });
                });

            modelBuilder.Entity("AmeliorateAegis.Models.LessonPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("TeacherId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("LessonPlans");
                });

            modelBuilder.Entity("AmeliorateAegis.Models.Parent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CentreId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DoB")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CentreId");

                    b.ToTable("Parents");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CentreId = 1L,
                            CreationTime = new DateTime(2021, 10, 10, 20, 24, 15, 323, DateTimeKind.Local).AddTicks(3001),
                            DoB = new DateTime(1994, 10, 10, 20, 24, 15, 323, DateTimeKind.Local).AddTicks(4999),
                            FirstName = "Jane",
                            LastName = "Pope"
                        },
                        new
                        {
                            Id = 2L,
                            CentreId = 2L,
                            CreationTime = new DateTime(2021, 10, 10, 20, 24, 15, 323, DateTimeKind.Local).AddTicks(6300),
                            DoB = new DateTime(1988, 10, 10, 20, 24, 15, 323, DateTimeKind.Local).AddTicks(6352),
                            FirstName = "Thembeka",
                            LastName = "Qweba"
                        },
                        new
                        {
                            Id = 3L,
                            CentreId = 3L,
                            CreationTime = new DateTime(2021, 10, 10, 20, 24, 15, 323, DateTimeKind.Local).AddTicks(6393),
                            DoB = new DateTime(1976, 10, 10, 20, 24, 15, 323, DateTimeKind.Local).AddTicks(6396),
                            FirstName = "Jane",
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 4L,
                            CentreId = 2L,
                            CreationTime = new DateTime(2021, 10, 10, 20, 24, 15, 323, DateTimeKind.Local).AddTicks(6399),
                            DoB = new DateTime(1967, 10, 10, 20, 24, 15, 323, DateTimeKind.Local).AddTicks(6401),
                            FirstName = "Jon",
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 5L,
                            CentreId = 1L,
                            CreationTime = new DateTime(2021, 10, 10, 20, 24, 15, 323, DateTimeKind.Local).AddTicks(6404),
                            DoB = new DateTime(1992, 10, 10, 20, 24, 15, 323, DateTimeKind.Local).AddTicks(6406),
                            FirstName = "Joshua",
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 6L,
                            CentreId = 3L,
                            CreationTime = new DateTime(2021, 10, 10, 20, 24, 15, 323, DateTimeKind.Local).AddTicks(6408),
                            DoB = new DateTime(1972, 10, 10, 20, 24, 15, 323, DateTimeKind.Local).AddTicks(6410),
                            FirstName = "Thandi",
                            LastName = "Newton"
                        },
                        new
                        {
                            Id = 7L,
                            CentreId = 2L,
                            CreationTime = new DateTime(2021, 10, 10, 20, 24, 15, 323, DateTimeKind.Local).AddTicks(6413),
                            DoB = new DateTime(1996, 10, 10, 20, 24, 15, 323, DateTimeKind.Local).AddTicks(6414),
                            FirstName = "Amanda",
                            LastName = "Qweba"
                        },
                        new
                        {
                            Id = 8L,
                            CentreId = 3L,
                            CreationTime = new DateTime(2021, 10, 10, 20, 24, 15, 323, DateTimeKind.Local).AddTicks(6417),
                            DoB = new DateTime(2000, 10, 10, 20, 24, 15, 323, DateTimeKind.Local).AddTicks(6419),
                            FirstName = "Amyoli",
                            LastName = "Soze"
                        },
                        new
                        {
                            Id = 9L,
                            CentreId = 1L,
                            CreationTime = new DateTime(2021, 10, 10, 20, 24, 15, 323, DateTimeKind.Local).AddTicks(6421),
                            DoB = new DateTime(1991, 10, 10, 20, 24, 15, 323, DateTimeKind.Local).AddTicks(6423),
                            FirstName = "Jongokhaya",
                            LastName = "Khwili"
                        },
                        new
                        {
                            Id = 10L,
                            CentreId = 3L,
                            CreationTime = new DateTime(2021, 10, 10, 20, 24, 15, 323, DateTimeKind.Local).AddTicks(6425),
                            DoB = new DateTime(1989, 10, 10, 20, 24, 15, 323, DateTimeKind.Local).AddTicks(6427),
                            FirstName = "Thandeka",
                            LastName = "Khehle"
                        });
                });

            modelBuilder.Entity("AmeliorateAegis.Models.Period", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Periods");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreationTime = new DateTime(2021, 10, 10, 20, 24, 15, 323, DateTimeKind.Local).AddTicks(7605),
                            Name = "Term 1"
                        },
                        new
                        {
                            Id = 2L,
                            CreationTime = new DateTime(2021, 10, 10, 20, 24, 15, 323, DateTimeKind.Local).AddTicks(9068),
                            Name = "Term 2"
                        },
                        new
                        {
                            Id = 3L,
                            CreationTime = new DateTime(2021, 10, 10, 20, 24, 15, 323, DateTimeKind.Local).AddTicks(9109),
                            Name = "Term 3"
                        },
                        new
                        {
                            Id = 4L,
                            CreationTime = new DateTime(2021, 10, 10, 20, 24, 15, 323, DateTimeKind.Local).AddTicks(9112),
                            Name = "Term 4"
                        });
                });

            modelBuilder.Entity("AmeliorateAegis.Models.Programme", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("CentreId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CentreId");

                    b.ToTable("Programs");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CentreId = 1L,
                            CreationTime = new DateTime(2021, 10, 10, 20, 24, 15, 324, DateTimeKind.Local).AddTicks(8500),
                            Name = "Literacy Development"
                        },
                        new
                        {
                            Id = 2L,
                            CentreId = 2L,
                            CreationTime = new DateTime(2021, 10, 10, 20, 24, 15, 325, DateTimeKind.Local).AddTicks(219),
                            Name = "Math And Science"
                        },
                        new
                        {
                            Id = 3L,
                            CentreId = 1L,
                            CreationTime = new DateTime(2021, 10, 10, 20, 24, 15, 325, DateTimeKind.Local).AddTicks(263),
                            Name = "Song And Music"
                        },
                        new
                        {
                            Id = 4L,
                            CentreId = 1L,
                            CreationTime = new DateTime(2021, 10, 10, 20, 24, 15, 325, DateTimeKind.Local).AddTicks(267),
                            Name = "Art And Music"
                        },
                        new
                        {
                            Id = 5L,
                            CentreId = 3L,
                            CreationTime = new DateTime(2021, 10, 10, 20, 24, 15, 325, DateTimeKind.Local).AddTicks(270),
                            Name = "Language And Speech"
                        });
                });

            modelBuilder.Entity("AmeliorateAegis.Models.ProgrammeCentre", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CentreId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("ProgramId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CentreId");

                    b.HasIndex("ProgramId");

                    b.ToTable("Pro_Centres");
                });

            modelBuilder.Entity("AmeliorateAegis.Models.ProgrammeEnrollment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("PupilId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PupilId");

                    b.ToTable("Pro_Enrollments");
                });

            modelBuilder.Entity("AmeliorateAegis.Models.ProgressReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Mark")
                        .HasColumnType("float");

                    b.Property<long>("PeriodId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProgramId")
                        .HasColumnType("bigint");

                    b.Property<long>("PupilId")
                        .HasColumnType("bigint");

                    b.Property<long>("TeacherId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId");

                    b.HasIndex("ProgramId");

                    b.HasIndex("PupilId");

                    b.HasIndex("TeacherId");

                    b.ToTable("ProgressReports");
                });

            modelBuilder.Entity("AmeliorateAegis.Models.Pupil", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CentreId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DoB")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TeacherId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CentreId");

                    b.HasIndex("ParentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Pupils");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CentreId = 1L,
                            CreationTime = new DateTime(2021, 10, 10, 20, 24, 15, 324, DateTimeKind.Local).AddTicks(3750),
                            DoB = new DateTime(2016, 10, 10, 20, 24, 15, 324, DateTimeKind.Local).AddTicks(5436),
                            FirstName = "Peter",
                            LastName = "Pope",
                            ParentId = 1L,
                            TeacherId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            CentreId = 2L,
                            CreationTime = new DateTime(2021, 10, 10, 20, 24, 15, 324, DateTimeKind.Local).AddTicks(7114),
                            DoB = new DateTime(2017, 10, 10, 20, 24, 15, 324, DateTimeKind.Local).AddTicks(7172),
                            FirstName = "Amahle",
                            LastName = "Qweba",
                            ParentId = 2L,
                            TeacherId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            CentreId = 3L,
                            CreationTime = new DateTime(2021, 10, 10, 20, 24, 15, 324, DateTimeKind.Local).AddTicks(7210),
                            DoB = new DateTime(2016, 10, 10, 20, 24, 15, 324, DateTimeKind.Local).AddTicks(7212),
                            FirstName = "Junior",
                            LastName = "Doe",
                            ParentId = 3L,
                            TeacherId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            CentreId = 2L,
                            CreationTime = new DateTime(2021, 10, 10, 20, 24, 15, 324, DateTimeKind.Local).AddTicks(7216),
                            DoB = new DateTime(2017, 10, 10, 20, 24, 15, 324, DateTimeKind.Local).AddTicks(7218),
                            FirstName = "Jerry",
                            LastName = "Doe",
                            ParentId = 4L,
                            TeacherId = 1L
                        },
                        new
                        {
                            Id = 5L,
                            CentreId = 1L,
                            CreationTime = new DateTime(2021, 10, 10, 20, 24, 15, 324, DateTimeKind.Local).AddTicks(7220),
                            DoB = new DateTime(2015, 10, 10, 20, 24, 15, 324, DateTimeKind.Local).AddTicks(7222),
                            FirstName = "JJ",
                            LastName = "Doe",
                            ParentId = 5L,
                            TeacherId = 1L
                        },
                        new
                        {
                            Id = 6L,
                            CentreId = 3L,
                            CreationTime = new DateTime(2021, 10, 10, 20, 24, 15, 324, DateTimeKind.Local).AddTicks(7224),
                            DoB = new DateTime(2017, 10, 10, 20, 24, 15, 324, DateTimeKind.Local).AddTicks(7225),
                            FirstName = "Mihle",
                            LastName = "Newton",
                            ParentId = 6L,
                            TeacherId = 1L
                        },
                        new
                        {
                            Id = 7L,
                            CentreId = 2L,
                            CreationTime = new DateTime(2021, 10, 10, 20, 24, 15, 324, DateTimeKind.Local).AddTicks(7228),
                            DoB = new DateTime(2016, 10, 10, 20, 24, 15, 324, DateTimeKind.Local).AddTicks(7229),
                            FirstName = "Sinazo",
                            LastName = "Qweba",
                            ParentId = 7L,
                            TeacherId = 1L
                        },
                        new
                        {
                            Id = 8L,
                            CentreId = 3L,
                            CreationTime = new DateTime(2021, 10, 10, 20, 24, 15, 324, DateTimeKind.Local).AddTicks(7232),
                            DoB = new DateTime(2015, 10, 10, 20, 24, 15, 324, DateTimeKind.Local).AddTicks(7233),
                            FirstName = "Buhle",
                            LastName = "Soze",
                            ParentId = 8L,
                            TeacherId = 1L
                        },
                        new
                        {
                            Id = 9L,
                            CentreId = 1L,
                            CreationTime = new DateTime(2021, 10, 10, 20, 24, 15, 324, DateTimeKind.Local).AddTicks(7235),
                            DoB = new DateTime(2017, 10, 10, 20, 24, 15, 324, DateTimeKind.Local).AddTicks(7237),
                            FirstName = "Khaya",
                            LastName = "Khwili",
                            ParentId = 9L,
                            TeacherId = 1L
                        },
                        new
                        {
                            Id = 10L,
                            CentreId = 3L,
                            CreationTime = new DateTime(2021, 10, 10, 20, 24, 15, 324, DateTimeKind.Local).AddTicks(7239),
                            DoB = new DateTime(2016, 10, 10, 20, 24, 15, 324, DateTimeKind.Local).AddTicks(7240),
                            FirstName = "Kubeka",
                            LastName = "Khehle",
                            ParentId = 10L,
                            TeacherId = 1L
                        });
                });

            modelBuilder.Entity("AmeliorateAegis.Models.Teacher", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DoB")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qualification")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreationTime = new DateTime(2021, 10, 10, 20, 24, 15, 324, DateTimeKind.Local).AddTicks(196),
                            DoB = new DateTime(1976, 10, 10, 20, 24, 15, 324, DateTimeKind.Local).AddTicks(1845),
                            FirstName = "Margaret",
                            LastName = "Van Hum",
                            Qualification = "Bachelor Of Education In Child Development"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("AmeliorateAegis.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<long?>("CentreId")
                        .HasColumnType("bigint");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("CentreId");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("AmeliorateAegis.Models.Attendance", b =>
                {
                    b.HasOne("AmeliorateAegis.Models.Pupil", "Pupil")
                        .WithMany()
                        .HasForeignKey("PupilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AmeliorateAegis.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AmeliorateAegis.Models.LessonPlan", b =>
                {
                    b.HasOne("AmeliorateAegis.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AmeliorateAegis.Models.Parent", b =>
                {
                    b.HasOne("AmeliorateAegis.Models.Centre", "Centre")
                        .WithMany()
                        .HasForeignKey("CentreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AmeliorateAegis.Models.Programme", b =>
                {
                    b.HasOne("AmeliorateAegis.Models.Centre", "Centre")
                        .WithMany()
                        .HasForeignKey("CentreId");
                });

            modelBuilder.Entity("AmeliorateAegis.Models.ProgrammeCentre", b =>
                {
                    b.HasOne("AmeliorateAegis.Models.Centre", "Centre")
                        .WithMany()
                        .HasForeignKey("CentreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AmeliorateAegis.Models.Programme", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AmeliorateAegis.Models.ProgrammeEnrollment", b =>
                {
                    b.HasOne("AmeliorateAegis.Models.Pupil", "Pupil")
                        .WithMany("Enrollments")
                        .HasForeignKey("PupilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AmeliorateAegis.Models.ProgressReport", b =>
                {
                    b.HasOne("AmeliorateAegis.Models.Period", "Period")
                        .WithMany()
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AmeliorateAegis.Models.Programme", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AmeliorateAegis.Models.Pupil", "Pupil")
                        .WithMany("Reports")
                        .HasForeignKey("PupilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AmeliorateAegis.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AmeliorateAegis.Models.Pupil", b =>
                {
                    b.HasOne("AmeliorateAegis.Models.Centre", "Centre")
                        .WithMany()
                        .HasForeignKey("CentreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AmeliorateAegis.Models.Parent", "Parent")
                        .WithMany("Pupils")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AmeliorateAegis.Models.Teacher", "Teacher")
                        .WithMany("Pupils")
                        .HasForeignKey("TeacherId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AmeliorateAegis.Models.ApplicationUser", b =>
                {
                    b.HasOne("AmeliorateAegis.Models.Centre", "Centre")
                        .WithMany()
                        .HasForeignKey("CentreId");
                });
#pragma warning restore 612, 618
        }
    }
}
